title: Formwork
description: 'Formwork is a simple, fast and flexible flat-file CMS that allows you to create and manage your website without the need for a database.'
footer: |-
    **© 2018-2025 – Formwork**

    Designed and made by [giuscris](https://github.com/giuscris) and [contributors](https://github.com/getformwork/formwork/graphs/contributors).
socialLinks:
    GitHub: 'https://github.com/getformwork/formwork'
    Discord: 'https://discord.gg/f7CnnaVdvH'
languages:
    available:
        - en
metadata:
    'og:title': 'Formwork CMS'
    'og:description': 'Formwork is a simple, fast and flexible flat-file CMS that allows you to create and manage your website without the need for a database.'
